# Generated by Django 6.1.1 on 2026-09-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_reservetion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetion',
            name='reservation_time',
        ),
    ]
